[package]
name = "avm"
version = "0.1.0"
edition = "2021"
authors = ["Ist's Programs", "Uni-Technologies"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
